In [1]:
from definitions import WEBDRIVER_PATH
from modules.plotting import plot_companies
from modules.classes import company
import pandas as pd
import re
import numpy as np

In [2]:
# Conversion from euro necessary
ubisoft = company('UBSFY', method = 'import')

In [3]:
ubisoft.statements['is']['statement']['total_revenue']

array([2218100., 2223800., 1594831., 1845522., 1731894.])

In [4]:
ubisoft.statements['is']['statement']['operating_expense']

array([1513200., 1498300., 1300444., 1308334., 1174515.])

In [5]:
ubisoft.convert_currency('EUR','USD')

{'2017': 1.1264083333333332,
 '2018': 1.18225,
 '2019': 1.1210041666666666,
 '2020': 1.1393666666666666,
 '2021': 1.1857291666666667}

In [6]:
ubisoft.statements['is']['statement']['total_revenue']

array([2498486., 2629088., 1787812., 2102726., 2053557.])

In [8]:
ubisoft.statements['is']['statement']['year_adjusted']

['2021', '2020', '2019', '2018', '2017']

In [ ]:
ea = company('EA', method = 'import')

In [ ]:
plot_companies([ubisoft, ea], 'total_revenue').show();

In [ ]:
ubisoft.plot_metrics(['total_revenue','operating_expense']).show();

In [ ]:
activision = company('ATVI', method = 'import')

In [ ]:
devolver = company('DEVO.L', method = 'import')

In [9]:
# Conversion from yen necessary
nintendo = company('NTDOY', method = 'import')

In [10]:
nintendo.statements['is']['statement']['total_revenue']

array([1.613658e+09, 1.758910e+09, 1.308519e+09, 1.200560e+09,
       1.055682e+09])

In [11]:
nintendo.convert_currency('JPY','USD')

{'2017': 0.008908961851413743,
 '2018': 0.009063701958698206,
 '2019': 0.009166197732901558,
 '2020': 0.00936655323757658,
 '2021': 0.009127661768831648}

In [12]:
nintendo.statements['is']['statement']['total_revenue']

array([14376018., 15942236., 11994144., 11245109.,  9635908.])

In [ ]:
# Conversion from yen necessary
squareenix = company('SQNXF', method = 'import')

In [ ]:
# Conversion from yen necessary
capcom = company('CCOEY', method = 'import')

In [ ]:
# Conversion from yen necessary
bandainamco = company('NCBDF', method = 'import')

In [ ]:
conversion = [['2019',1.5],['2020',1.6],['2021',1.4]]

In [ ]:
conversion_array = np.asarray(conversion)
conversion_filter = np.asarray(['2020','2021'])
conversion_array

In [ ]:
mask = np.in1d(conversion_array[:,0], conversion_filter)
conversion_array[mask]